config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'iregular_holidays/index'
  end
  namespace :user do
    get 'task_courses/index'
  end
  namespace :user do
    get 'calendars/show'
  end
  namespace :user do
    get 'staff_shifts/index'
    get 'staff_shifts/edit'
  end
  get 'tasks/index'
  root to: 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # user権限(店長)
  scope module: :user do
    resources :users, only: [] do
      get "calendar/:id/calendar_preview", to: "calendars#calendar_preview", as: "calendar_preview"
      resources :calendars do
        get "dashboard", to: "top#dashboard"
        resource :calendar_config
        resources :staffs
        resources :task_courses
      end
    end
    resources :calendars, only: [] do
      resources :iregular_holidays
      resources :staffs, only: [] do
        resources :staff_shifts
      end
    end
  end

  # public権限
  scope module: :public do
    get "task_create", to: "tasks#task_create", as: :task_create
    resources :calendars, only: [] do
      resources :tasks, except: [:show]
    end
  end

end

app/controllers/user/base.rb
class User::Base < ApplicationController
  # before_action :authenticate_user_staff!
  # before_action :authenticate_current_user!
  # before_action :initial_setting_complete?
  # before_action :agreement_plan?

  layout 'user'

  def calendar
    calendar_params = params[:calendar_id] || params[:id]
    @calendar = Calendar.find_by(id: calendar_params)
    # @q = Task.only_valid.by_calendar(@calendar).ransack(params[:q])
  end

  def create_calendar_staffs_tasks(calendar)
    calendar.staffs.each do |staff|
    desplay_month_term = ENV['CALENDAR_DISPLAY_TERM'].to_i
    start_term = Date.current.beginning_of_month
    end_term = Date.current.weeks_since(desplay_month_term + 1).end_of_month
    last_shift = staff.staff_shifts.order(:work_date).last
    StaffShiftsCreator.call(start_term, end_term, staff)
    end
  end

  def authenticate_user_staff!
    redirect_to new_user_session_url unless current_user || current_staff
  end

  def authenticate_current_user!
    if current_staff
    flash[:danger] = '権限がありません'
    redirect_to user_calendar_dashboard_url(current_user, params[:calendar_id])
    end
  end

  def check_staff_course_exsist!
      if @calendar.staffs.none? && @calendar.task_courses.none?
      @cation = '1'
      elsif @calendar.staffs.none?
      @cation = '2'
      elsif @calendar.task_courses.none?
      @cation = '3'
      end
  end

  def initial_setting_complete?
      if current_user.calendars.none?
      flash[:danger] = '初期設定が完了していません。'
      redirect_to introductions_new_calendar_url
      elsif current_user.calendars.first.staffs.none?
      flash[:danger] = '初期設定が完了していません。'
      redirect_to introductions_new_staff_url
      elsif current_user.calendars.first.task_courses.none?
      flash[:danger] = '初期設定が完了していません。'
      redirect_to introductions_new_staff_url
      end
  end

  def agreement_plan?
      if current_user.order_plans.none?
      flash[:danger] = 'プランを選択してください。'
      redirect_to choice_plan_url
      end
  end
end

app/controllers/user/calendar_configs_controller.rb
class User::CalendarConfigsController < User::Base
  before_action :calendar

  def update
    @calendar_config = Calendar.find_by(id: params[:calendar_id]).calendar_config
    respond_to do |format|
      if @calendar_config.update(calendar_config_regular_holidays_params)
        update_staff_regular_holiday if params[:all_staff_update] == 'true'
        format.html { redirect_to user_calendar_url(current_user, @calendar), notice: '詳細設定を更新しました。' }
      else
        format.html { redirect_to user_calendar_url(current_user, @calendar), notice: '詳細設定の更新に失敗しました。' }
      end
    end
  end

  private

  def calendar_config_regular_holidays_params
    params.require(:calendar_config).permit(:capacity, :interval_time, :booking_message, :booking_link, regular_holidays_attributes: %i[holiday_flag id business_start_at business_end_at is_rest rest_start_time rest_end_time])
  end

  def update_staff_regular_holiday
    @calendar_config.regular_holidays.each do |regular_holiday|
      regular_holiday.staff_regular_holidays.each do |holiday|
        holiday.update(is_holiday: regular_holiday.holiday_flag,
                       work_start_at: regular_holiday.business_start_at,
                       work_end_at: regular_holiday.business_end_at,
                       rest_start_time: regular_holiday.rest_start_time,
                       rest_end_time: regular_holiday.rest_end_time,
                       is_rest: regular_holiday.is_rest)
      end
    end
  end
end

app/controllers/user/calendars_controller.rb
class User::CalendarsController < User::Base
  before_action :calendar, except: %i[new create]

  def new
    @calendar = current_user.calendars.build
  end

  def create
    @calendar = current_user.calendars.build(params_calendar)
    if @calenar.save
    end
  end

  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @calendar.update(params_calendar)
      # スタッフのシフトを作成（base.rbに記載）
      create_calendar_staffs_tasks(@calendar) if @calendar.saved_change_to_display_week_term?
      flash[:succese] = 'カレンダーの設定を更新しました。'
      redirect_to user_calendar_url(@user, @calendar)
    else
      @calendar.reload
      render action: :show
    end
  end

  def update_is_released
    @calendar = Calendar.find_by(id: params[:id])
    if params[:commit] == '公開にする'
      if @calendar.update(is_released: true)
        flash[:succese] = 'カレンダーを公開しました'
        redirect_to user_calendar_dashboard_url(current_user, @calendar)
      end
    else
      if @calendar.update(is_released: false)
        flash[:succese] = 'カレンダーを非公開にしました'
        redirect_to user_calendar_dashboard_url(current_user, @calendar)
      end
    end
  rescue StandardError
    flash[:danger] = '更新できませんでした'
    redirect_to user_calendar_dashboard_url(current_user, @calendar)
  end

  def calendar_preview
    task = Task.new
    @calendar = Calendar.find_by(public_uid: params[:id])
    staff_id = params[:staff_id] || @calendar.staffs.first.id
    @staff = Staff.find(staff_id)
    @task_course = @calendar.task_courses.first
    @user = @calendar.user
    @times = time_interval(@calendar)

    @today = Time.current
    # DBタスクデータを引き出す
    @events = @staff.tasks.map { |task| [task.start_time, task.end_time] }
    # googleカレンダーのデータを同期
    @google_events = SyncCalendarService.new(task, @staff, @calendar).read_event if @staff.google_calendar_id
    one_month = [*Date.current.days_since(@calendar.start_date)..Date.current.weeks_since(@calendar.display_week_term)]
    @month = Kaminari.paginate_array(one_month).page(params[:page]).per(@calendar.end_date)
  end

  private

  def params_calendar
    params.require(:calendar).permit(:calendar_name, :start_date, :end_date, :display_week_term, :public_uid, :is_released, :address, :phone, :start_time, :end_time, :display_time, :display_interval_time, :message, :picture)
  end

  def time_interval(calendar)
    start_time = calendar.start_time
    end_time = calendar.end_time
    interval_time = calendar.display_interval_time
    array = []
    1.step do |i|
      array.push(Time.parse("#{start_time}:00") + interval_time.minutes * (i - 1))
      break if Time.parse("#{start_time}:00") + interval_time.minutes * (i - 1) == Time.parse("#{end_time}:00")
    end
    array
  end
end

app/controllers/user/iregular_holidays_controller.rb
class User::IregularHolidaysController < User::Base
  before_action :calendar
  before_action :iregular_holiday, only: %i[edit update destroy]

  def index
    @json_data = json_data
    @regular_holiday = calendar_config.regular_holidays
  end

  def new
    @iregular_holiday = IregularHoliday.new(calendar_config_id: calendar_config.id, date: params[:date])
  end

  def create
    @iregular_holiday = IregularHoliday.new(iregular_holiday_params)
    @iregular_holiday.calendar_config = calendar_config
    if @iregular_holiday.save
      flash[:success] = '休日を作成しました'
      redirect_to calendar_iregular_holidays_path(@calendar)
    else
      if @iregular_holiday.errors
        @iregular_holiday.errors.full_messages.each do |msg|
          flash[:danger] = msg
        end
      else
        flash[:danger] = '休日を作成できませんでした'
      end
      redirect_to calendar_iregular_holidays_path(@calendar)
    end
  end

  def edit; end

  def update
    if @iregular_holiday.update(iregular_holiday_params)
      flash[:success] = '休日を更新しました'
      redirect_to calendar_iregular_holidays_path(@calendar)
    else
      if @iregular_holiday.errors
        @iregular_holiday.errors.full_messages.each do |msg|
          flash[:danger] = msg
        end
      else
        flash[:danger] = '休日を更新できませんでした'
      end
      redirect_to calendar_iregular_holidays_path(@calendar)
    end
  end

  def destroy
    if @iregular_holiday.destroy
      flash[:success] = '休日を削除しました'
      redirect_to calendar_iregular_holidays_path(@calendar)
    else
      flash[:danger] = '休日を削除できませんでした'
      redirect_to calendar_iregular_holidays_path(@calendar)
    end
  end

  private

  def iregular_holiday_params
    params.require(:iregular_holiday).permit(:date, :description, :id, :calendar_config_id)
  end

  def calendar_config
    @calendar_config = @calendar.calendar_config
  end

  def iregular_holiday
    @iregular_holiday = IregularHoliday.find(params[:id])
  end

  def regular_holidays
    regular_holidays = calendar_config.regular_holidays.where(holiday_flag: true)
    a = begin
            [*Date.current.beginning_of_month..Date.current.since(6.months).end_of_month].map do |date|
              day = %w[日 月 火 水 木 金 土][date.wday]
              if regular_holidays.find_by(day: day)
                {
                  start: l(date, format: :to_json),
                  end: l(date.tomorrow, format: :to_json),
                  overlap: false,
                  rendering: 'background'
                }
              else
                {

                }
              end
            end
        rescue StandardError
          nil
          end
  end

  def iregular_holidays
    calendar_config.iregular_holidays.map do |date|
      {
        title: '休日',
        start: l(date.date, format: :to_json),
        end: l(date.date.tomorrow, format: :to_json),
        overlap: false,
        id: date.id
        # rendering: 'background'
      }
    end
  end

  def staff_shifts(staff)
    staff.staff_shifts.map do |shift|
      {
        start: l(shift.work_start_time, format: :to_work_json),
        end: l(shift.work_end_time, format: :to_work_json),
        rendering: 'background'
      }
    end
  rescue StandardError
    nil
  end

  def json_data
    hash = {
      "start_date": Date.current.beginning_of_month,
      "end_date": Date.current.since(6.months).end_of_month,
      "holidays": regular_holidays + iregular_holidays
    }.to_json
  end
end

app/controllers/user/staff_shifts_controller.rb
class User::StaffShiftsController < User::Base
  before_action :set_staff_shift, only: %i[edit update destroy]
  before_action :set_staff, only: %i[index edit update destroy]
  before_action :calendar, only: %i[index edit update destroy]

  def index
    @month = params[:month]&.to_datetime || DateTime.current
    @staff_shifts = @staff.staff_shifts.where(work_date: @month.all_month)
    start_of_month = @month.beginning_of_month
    end_of_month = @month.end_of_month
    regular_holidays = get_regular_holidays
  end

  def edit
  end

  def update
    respond_to do |format|
      if @staff_shift.update(staff_shift_params)
        format.html { redirect_to calendar_staff_staff_shifts_url(@calendar, @staff), notice: 'シフトを更新しました。' }
        format.json { render :show, status: :ok, location: @staff_shift }
      else
        format.html { redirect_to calendar_staff_staff_shifts_url(@calendar, @staff), notice: 'シフトを更新できませんでした。' }
        format.json { render json: @staff_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_staff_shift
    @staff_shift = StaffShift.find(params[:id])
  end

  def set_staff
    @staff = Staff.find(params[:staff_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def staff_shift_params
    params.require(:staff_shift).permit(:work_start_time, :work_end_time, :staff_id)
  end

  def get_regular_holidays
    regular_holidays = @staff.calendar.calendar_config.regular_holidays
  end
end

app/controllers/user/staffs_controller.rb
class User::StaffsController < User::Base
  before_action :authenticate_user!
  before_action :calendar
  before_action :staff, only: %i[show edit update destroy]

  def index
    @staffs = @calendar.staffs
  end

  def show; end

  def new
    @staff = Staff.new
  end

  def create
    @staff = @calendar.staffs.build(staff_params)
    if @staff.save
      flash[:success] = 'スタッフを登録しました'
      redirect_to user_calendar_staffs_url(current_user, @calendar)
    else
      flash[:danger] = 'スタッフを登録できませんでした。'
      redirect_to user_calendar_staffs_url(current_user, @calendar)
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @staff.update(staff_params_update)
        flash[:success] = 'スタッフを更新しました'
        format.html { redirect_to edit_user_calendar_staff_url(current_user, @calendar, @staff) }
        # format.json { render :show, status: :ok, location: @staff }
      else
        flash[:danger] = 'スタッフを更新できませんでした'
        format.html { redirect_to edit_user_calendar_staff_url(current_user, @calendar, @staff) }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @staff.tasks.where('start_time > ?', Time.current).any?
      flash[:danger] = "#{@staff.name}の予約が#{@staff.tasks.where('start_time > ?', Time.current).count}件残っているので削除できません。予約をキャンセルするか、担当者を変更してください。"
      redirect_to user_calendar_staffs_url(current_user, @calendar)
    else
      @staff.destroy
      flash[:danger] = 'スタッフを削除しました'
      redirect_to user_calendar_staffs_url(current_user, @calendar)
    end
  end

  def staffs_shifts
    @staffs = @calendar.staffs
  end

  private

  def staff_params_update
    params.require(:staff).permit(:name, :description, :email, :picture, staff_regular_holidays_attributes: %i[is_holiday work_start_at work_end_at id is_rest rest_start_time rest_end_time])
  end

  def staff_params
    params.require(:staff).permit(:name, :description, :email, :staff_part)
  end

  def staff
    @staff = Staff.find(params[:id])
  end

end

app/controllers/user/store_members_controller.rb
class User::StoreMembersController < User::Base
  before_action :calendar
  # skip_before_action :authenticate_current_user!

  def index
    @member_q = @calendar.store_members.ransack(params[:q])
    @store_members = @member_q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @store_member = StoreMember.find(params[:id])
    @tasks = @store_member.tasks.order(start_time: 'desc')
    @member_log = MemberLog.new()
    @member_logs = @store_member.member_logs.order(id: "desc")
    @log_picture = @member_log.log_pictures.build
  end

  def store_member_task_show
    @task = Task.only_valid.find(params[:id])
  end

  def update
    @store_member = StoreMember.find(params[:id])
    if @store_member.update(params_store_member)
      @status = 200
    else
      @status = 400
    end
  end

  def update_task
    @task = Task.only_valid.find(params[:id])
    if @task.update(params_member_task)
      flash[:success] = '会員の予定を更新しました。'
      redirect_to calendar_store_member_url(@calendar, @task.store_member)
    else
      flash[:danger] = '会員の予定を更新できませんでした。'
      redirect_to calendar_store_member_url(@calendar, @task.store_member)
    end
  end

  private

  def params_store_member
    params.require(:store_member).permit(:memo, :name, :email, :phone)
  end

  def params_member_task
    params.require(:task).permit(:memo)
  end
end

app/controllers/user/top_controller.rb
class User::TopController < User::Base
  before_action :authenticate_user!
  before_action :calendar

  def dashboard
    @tasks = Task.all
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/helpers/user/calendars_helper.rb
module User::CalendarsHelper
end

app/helpers/user/iregular_holidays_helper.rb
module User::IregularHolidaysHelper
end

app/helpers/user/staff_shifts_helper.rb
module User::StaffShiftsHelper
end

app/views/user/user_tasks/_new_staff_rest_form.html.erb
<%= form_for staff_rest_time, url:user_calendar_staff_rest_times_path(current_user, calendar) do |f| %>
    <%= fields_for staff_rest_time.staff_shift do |shift| %>
        <div class="form-group">
            <label for="exampleInputPassword1">スタッフ</label>
            <%= shift.collection_select :staff_id, calendar.staffs, :id, :name, {prompt: ""},  class: "form-control form_style", required: "required" %>
        </div>
        <%= shift.hidden_field :work_date, value: staff_rest_time.rest_start_time.to_date %>
    <% end %>
    <div class="form-group">
        <label for="exampleInputPassword1">開始時間</label>
        <%= raw sprintf(
                    f.datetime_select(
                        :rest_start_time,
                        use_month_numbers: true,
                        )
                )
                %>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">終了時間</label>
        <%= raw sprintf(
                    f.datetime_select(
                        :rest_end_time,
                        use_month_numbers: true,
                        )
                )
                %>
    </div>
    <%= f.submit "登録する", class:"btn btn-primary btn_style load_btn_user_booking", data:{confirm:"スタッフの休憩を登録しますか？"} %>
<% end %>

app/views/user/user_tasks/_new_task_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">新規予約フォーム</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
        <span aria-hidden="true">&times;</span>
      </button>
    </div><!-- /.modal-header -->
    <div class="modal-body">
      <div class="form_area">
          <ul id="myTab" class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                  <a href="#task" id="home-tab" class="nav-link active" role="tab" data-toggle="tab" aria-controls="home" aria-selected="true">予約登録</a>
              </li>
              <li class="nav-item">
                  <a href="#sub_task" id="profile-tab" class="nav-link" role="tab" data-toggle="tab" aria-controls="profile" aria-selected="false">仮予約</a>
              </li>
              <li class="nav-item">
                  <a href="#staff_rest" id="profile-tab" class="nav-link" role="tab" data-toggle="tab" aria-controls="profile" aria-selected="false">スタッフ休憩登録</a>
              </li>
          </ul>

          <!-- パネル部分 -->
          <div id="myTabContent" class="tab-content mt-3">
            <div id="task" class="tab-pane active" role="tabpanel" aria-labelledby="home-tab">
                <%= render 'new_task_form', task: task, calendar: calendar, store_member: store_member %>
            </div>
            <div id="sub_task" class="tab-pane" role="tabpanel" aria-labelledby="profile-tab">
                <%= render 'new_sub_task_form', task: task, calendar: calendar, store_member: store_member %>
            </div>
            <div id="staff_rest" class="tab-pane" role="tabpanel" aria-labelledby="profile-tab">
                <%= render 'new_staff_rest_form', calendar: calendar, staff_rest_time: staff_rest_time %>
            </div>
          </div>
      </div>
    </div><!-- /.modal-body -->
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" >閉じる</button>
    </div><!-- /.modal-footer -->
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/user/user_tasks/_task_modal.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= task.store_member.name %>様:<%= l task.start_time, format: :middle %>~</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
      </div><!-- /.modal-header -->
      <%= form_for task, url: user_calendar_user_task_path(current_user, task.calendar, task) do |f| %>
      <div class="modal-body">
        <% member = task.store_member %>
          <table class="table table-sm">
            <tbody>
              <%= fields_for member do |f| %>
                <tr>
                  <th scope="row">名前</th>
                  <td><%= link_to member.name, calendar_store_member_path(member.calendar, member), class:"btn btn-info btn-sm" %>  <%= link_to "次回予約をする", user_calendar_dashboard_path(current_user, task.calendar, staff_id: task.staff_id, store_member_id: task.store_member.id)%></td>
                </tr>
                <tr>
                  <th scope="row">メールアドレス</th>
                  <td><%= member.email %></td>
                </tr>
                <tr>
                  <th scope="row">電話番号</th>
                  <td><%= member.phone %></td>
                </tr>
              <% end %>

                <tr>
                  <th scope="row">予約開始時間</th>
                  <td>
                    <p class="disabled_form"><%= l(task.start_time, format: :very_short) %></p>
                    <P class="display_none">
                      <%= f.datetime_select(
                          :start_time,
                          # discard_day: true,
                          # discard_month: true,
                          # discard_year: true,
                          ) %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">予約終了時間</th>
                  <td>
                    <p class="disabled_form"><%= l(task.end_time, format: :very_short) %></p>
                    <P class="display_none">
                      <%= f.datetime_select(
                          :end_time,
                          # discard_day: true,
                          # discard_month: true,
                          # discard_year: true,
                          ) %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">予約コース</th>
                  <td>
                    <p class="disabled_form"><%= task.task_course.title %></p>
                    <P class="display_none">
                      <%= f.collection_select :task_course_id, task.calendar.task_courses, :id, :title, {prompt: ""},  class: "form-control form_style display_none", required: "required" %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">担当者名</th>
                  <td>
                    <p class="disabled_form"><%= @task.staff_name %></p>
                    <P class="display_none">
                      <%= f.collection_select :staff_id, task.calendar.staffs, :id, :name, {prompt: ""},  class: "form-control form_style display_none", required: "required" %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">ご要望</th>
                  <td>
                    <%= simple_format(task.request, class: 'disabled_form') %>
                    <P class="display_none">
                      <%= f.text_area :request, class: "form-control form_style display_none" %>
                    </p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">メモ</th>
                  <td>
                    <%= simple_format(task.memo, class: 'disabled_form') %>
                    <P class="display_none">
                      <%= f.text_area :memo, class: "form-control form_style display_none" %>
                    </p>
                  </td>
                </tr>
                <tr class="display_none">
                  <th scope="row">お客様に通知する場合はチェックを入れてください</th>
                  <td>
                      <%= check_box_tag :is_send_notice_to_member %>
                  </td>
                </tr>
            </tbody>
          </table>
      </div><!-- /.modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-success" id="start_edit_btn">編集する</button>
        <%= link_to "キャンセル", user_calendar_user_task_path(current_user, task.calendar, task), method: :delete, class:"btn btn-outline-danger btn-sm display_none", data: {confirm: "キャンセルを行うとお客様に通知が行きます。"} %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" >閉じる</button>
        <%= f.submit "更新", class:"btn btn-primary display_none", data: {confirm: "内容を更新しますか？"} %>
      </div><!-- /.modal-footer -->
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

<script>
  // ボタンを押して、編集が可能になる
  $('#start_edit_btn').on('click', function() {
    $(".disabled_form").css("display","none")
    $(".display_none").removeClass("display_none");
    $(this).remove();
  });
</script>

app/views/user/user_tasks/index.html.erb
<h1>予約一覧</h1>
<%= search_form_for @q, url: user_calendar_user_tasks_path(current_user, @calendar) do |f| %>
  <label>名前or電話番号</label>
  <%= f.search_field :store_member_name_or_store_member_phone_cont, class: "form-control" %>
  <label>過去の予約を除外する</label>
  <% if params[:except_past_task] %>
    <%=check_box_tag :except_past_task, {} ,{:checked => true }%><br>
  <% else %>
    <%=check_box_tag :except_past_task%><br>
  <% end %>
  <%= f.submit "検索", class:"btn btn-primary load_btn" %>
<% end %>

<%= paginate @tasks %>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= sort_link(@q, :name, "名前") %></th>
        <th><%= sort_link(@q, :email, "email") %></th>
        <th><%= sort_link(@q, :phone, "電話番号") %></th>
        <th><%= sort_link(@q, :start_time, "予約時間") %></th>
        <th></th>
        <th><%= sort_link(@q, :created_at, "受付時間") %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.store_member.name %></td>
          <td><%= task.store_member.email %></td>
          <td><%= task.store_member.phone %></td>
          <td><%= reservation_date(task) %></td>
          <td>
            <%= link_to "カレンダーへ", user_calendar_dashboard_path(current_user, @calendar, staff_id: task.staff.id, task_id: task.id), class:"btn btn-outline-primary load_btn" if task.staff %>
            <%= link_to "キャンセル", user_calendar_user_task_path(current_user, @calendar, task), class:"btn btn-secondary btn_style", method: :delete ,data: {confirm: "本当にキャンセルを行いますか？" } %>
          </td>
          <td><%= l(task.created_at, format: :long) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/user/user_tasks/new.js.erb
$("#user_new_task_modal").html("<%= escape_javascript(render 'new_task_modal', task: @task,
                                                                               calendar: @calendar,
                                                                               store_member: @store_member,
                                                                               staff_rest_time: @staff_rest_time ) %>")
$("#user_new_task_modal").modal("show")

app/views/user/user_tasks/show.js.erb
$("#user_task_modal").html("<%= escape_javascript(render 'task_modal', task: @task ) %>")
$("#user_task_modal").modal("show")