config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'iregular_holidays/index'
  end
  namespace :user do
    get 'task_courses/index'
  end
  namespace :user do
    get 'calendars/show'
  end
  namespace :user do
    get 'staff_shifts/index'
    get 'staff_shifts/edit'
  end
  get 'tasks/index'
  root to: 'home#index'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # user権限(店長)
  scope module: :user do
    resources :users, only: [] do
      get "calendar/:id/calendar_preview", to: "calendars#calendar_preview", as: "calendar_preview"
      resources :calendars do
        get "dashboard", to: "top#dashboard"
        resource :calendar_config
        resources :staffs
        resources :task_courses
      end
    end
    resources :calendars, only: [] do
      resources :iregular_holidays
      resources :staffs, only: [] do
        resources :staff_shifts
      end
    end
  end

  # public権限
  scope module: :public do
    get "task_create", to: "tasks#task_create", as: :task_create
    resources :calendars, only: [] do
      resources :tasks, except: [:show]
    end
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message %>
    <div class="alert-secondary share_text_centering alert alert-<%= message_type %>"><%= message.html_safe %></div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/users/1/calendars/1/dashboard"><%= Calendar.find(1).calendar_name %></a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            設定
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item"><%= link_to "ユーザー設定", edit_user_registration_path, class: "dropdown-item" %></a></li>
            <li><a class="dropdown-item"><%= link_to "カレンダー設定", user_calendar_path(current_user, 1), class:"dropdown-item" %></a></li>
            <li><a class="dropdown-item"><%= link_to "休日設定", calendar_iregular_holidays_path(1), class:"dropdown-item load_btn" %></a></li>
            <li><a class="dropdown-item"><%= link_to "スタッフ設定", user_calendar_staffs_path(current_user, 1), class: "dropdown-item" %></a></li>
            <li><a class="dropdown-item"><%= link_to "コース設定", user_calendar_task_courses_path(current_user, @calendar), class: "dropdown-item" %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item"><%= link_to "ログアウト", sign_out_path, class: "dropdown-item" %></a></li>
          </ul>
        </li>

        <!--
        <%# 会員一覧 %>
        <li class="nav-item">
          <%= link_to calendar_store_members_path(@calendar), class:"nav-link load_btn" do %>
            <i class="far fa-address-book"></i>会員一覧
          <% end %>
        </li>
        -->

        <%# 予約一覧 %>
        <li class="nav-item">
          <%= link_to user_calendar_user_tasks_path(current_user, @calendar), class:"nav-link load_btn" do %>
            <i class="fa fa-calendar" aria-hidden="true"></i>予約一覧
          <% end %>
        </li>

        <%# カレンダーリリース状況 %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="shiftDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-intro="オーバーレイで表示するテキスト" data-position="right">
            <i class="fa fa-ravelry" aria-hidden="true"></i><%= @calendar.display_release %>
          </a>
          <div class="dropdown-menu" aria-labelledby="shiftDropdown">
            <% if @calendar.is_released %>
              <%= link_to "非公開にする", user_calendar_update_is_released_path(current_user, @calendar, commit:"非公開にする"), class:"dropdown-item load_btn", method: :patch %>
            <% else %>
              <%= link_to "カレンダーを公開する", user_calendar_update_is_released_path(current_user, @calendar, commit:"公開にする"), class:"dropdown-item load_btn", method: :patch %>
            <% end %>
          </div>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

app/views/layouts/_help_modal.html.erb
<div class="help_modal">
  <%= link_to "##", type:"button", data:{toggle:"modal", target:"#HelpModal"}, class:"fixed_btn", id:"fab" do %>
    <i class="fas fa-question"></i>
  <% end %>
  <!-- Modal -->
  <div class="modal fade" id="HelpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-width" role="document">
      <div class="modal-content">
        <div class="modal-body p-0">
          <div class="accordion" id="accordionExample">
            <% @help_urls.each.with_index do |url, index| %>
              <div class="card">
                <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                  <h5 class="mb-0 over-scroll">
                    <button class="btn btn-link" type="button">
                      <%= url[0] %>  <i class="far fa-hand-point-down"></i>
                    </button>
                  </h5>
                </div>

                <div id="collapse<%= index %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                  <div class="card-body p-0">
                    <iframe id="ston-CgZCfgcw8G" width="100%" height="815" frameBorder="0" name="StonlyExplanation" allowfullscreen src="<%= url[1] %>"> </iframe>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

app/views/layouts/_user_layout.html.erb
<div class="container">
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
</div>

<style>
.containar {
  width: 100%;
  padding-right: 60px;
  padding-left: 60px;
  margin-right: auto;
  margin-left: auto;
  margin-top:30px;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/plane.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="FXpzPpHGDRqmupmcC64f40VBjdgwxqG_zcPZHRM0dY0" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>Smart予約</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'public', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/libphonenumber-js/1.1.10/libphonenumber-js.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
    <script type="text/javascript">
    $(window).bind("unload",function(){});
    </script>
  </head>
  <body>
    <div id="overlay">
      <div class="cv-spinner">
        <span class="spinner"></span>
      </div>
    </div>
      <header class="">

      </header>
      <div class="container">
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="FXpzPpHGDRqmupmcC64f40VBjdgwxqG_zcPZHRM0dY0" />
    <title>Smart予約</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/user_layout' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>